# Generated by Django 2.0.6 on 2018-06-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=200)),
                ('club_content', models.CharField(max_length=10000)),
                ('club_link', models.CharField(max_length=200)),
                ('club_image_name', models.CharField(max_length=200)),
            ],
        ),
    ]
