# Generated by Django 2.0.5 on 2018-06-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='image_name',
            field=models.CharField(default='image', max_length=100),
            preserve_default=False,
        ),
    ]
