# Generated by Django 2.0.6 on 2018-06-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=1000)),
            ],
        ),
    ]
