# Generated by Django 2.0.6 on 2018-06-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20180626_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagelink',
            field=models.FileField(upload_to=''),
        ),
    ]
