# Generated by Django 2.0.6 on 2018-06-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180626_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='imagelink',
            new_name='image',
        ),
    ]
